# pull official base image
FROM debian:bullseye

RUN apt-get update -qq && apt-get install -y build-essential curl libpq-dev
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash \
  && apt-get update && apt-get install -y nodejs && rm -rf /var/lib/apt/lists/*
RUN npm install -g yarn

ENV PATH /app/node_modules/.bin:$PATH
COPY . /app
WORKDIR /app

RUN yarn install

EXPOSE 3002
EXPOSE 3035

